name: benchmark

on:
  push:
  workflow_dispatch:

permissions:
  # deployments permission to deploy GitHub pages website
  deployments: write
  # contents permission to update benchmark contents in gh-pages branch
  contents: write

jobs:
  benchmark:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
      - uses: actions/setup-node@v3
        with:
          # Fix the version to stabilize results.
          node-version: 16.14.0
          cache: 'pnpm'

      - run: pnpm install

      - name: pnpm run build
        run: pnpm run build

      - name: pnpm run postbuild:benchmark
        run: pnpm run postbuild:benchmark

      - name: Convert jsonl to json
        run: jq -s '.' benchmark/result.jsonl > benchmark/result.json

      - name: Upload benchmark
        uses: benchmark-action/github-action-benchmark@v1
        with:
          tool: customSmallerIsBetter
          output-file-path: benchmark/result.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: ${{ github.ref == 'refs/heads/main' }}
          comment-on-alert: true
          fail-on-alert: true
          alert-threshold: '300%'
          # for test
          # comment-always: true
