name: benchmark

on:
  push:
  workflow_dispatch:

permissions:
  # deployments permission to deploy GitHub pages website
  deployments: write
  # contents permission to update benchmark contents in gh-pages branch
  contents: write

jobs:
  benchmark:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          # Fix the version to stabilize results.
          node-version: 16.14.0

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: cache
        with:
          path: |
            **/node_modules
            ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: v1-${{ runner.os }}-16.14.0-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: v1-${{ runner.OS }}-16.14.0-yarn-

      - name: yarn install --frozen-lockfile
        run: yarn install --frozen-lockfile
        if: steps.cache.outputs.cache-hit != 'true'

      - name: yarn run build
        run: yarn run build

      - name: yarn run postbuild:benchmark
        run: yarn run postbuild:benchmark

      - name: Convert jsonl to json
        run: jq -s '.' benchmark/result.jsonl > benchmark/result.json

      - name: Upload benchmark
        uses: benchmark-action/github-action-benchmark@v1
        with:
          tool: customSmallerIsBetter
          output-file-path: benchmark/result.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: ${{ github.ref == 'refs/heads/main' }}
          comment-on-alert: true
          fail-on-alert: true
          alert-threshold: '150%'
          # for test
          comment-always: true
