name: ci-node

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'pnpm'

      - run: pnpm install

      - run: pnpm run lint

  test:
    strategy:
      fail-fast: false
      matrix:
        node: [14, 16]
        eslint: ['7.0.0', '^7.0.0', '8.0.0', '^8.0.0']
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      # To avoid differences in snapshot tests.
      - run: git config --global core.autocrlf false
        if: ${{ matrix.os == 'windows-latest' }}

      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: 'pnpm'

      - name: Change ESLint version
        run: pnpm add -D eslint@${{ matrix.eslint }}

      - name: pnpm run test
        run: pnpm run test

      - name: pnpm run build
        run: pnpm run build

      - name: pnpm run postbuild:test
        run: pnpm run postbuild:test
        # Currently the E2E test is written in bash shell script,
        # so it is difficult to run on windows. Therefore,
        # we are temporarily skipping the E2E test on windows.
        # TODO: Enable E2E test on windows.
        if: ${{ matrix.os != 'windows-latest' }}
